# Generated by Django 5.2.3 on 2026-04-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_staff_image_staff_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='background_image',
        ),
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_images/'),
        ),
    ]
