# Generated by Django 5.2.3 on 2026-04-04 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_staff_background_image_staff_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause_start', models.DateTimeField()),
                ('pause_end', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='myapp.task')),
            ],
        ),
    ]
