# Generated by Django 6.0.3 on 2026-04-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_task_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='worked_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
