# Generated by Django 6.0.3 on 2026-04-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_task_worked_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expected_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
