# Generated by Django 6.0.3 on 2026-04-07 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_task_exceeded_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='exceeded_time',
        ),
    ]
