# Generated by Django 6.0.3 on 2026-04-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_task_exceeded_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('paused', 'Paused'), ('completed', 'Completed'), ('exceeded', 'Exceeded')], default='pending', max_length=20),
        ),
    ]
