# Generated by Django 6.0.3 on 2026-04-28 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_timeextensionrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeExtensionRequest',
        ),
    ]
