# Generated by Django 6.0.3 on 2026-04-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_timeextensionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='worked_before_extension',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
