# Generated by Django 6.0.3 on 2026-04-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_task_worked_before_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='extension_resumed',
            field=models.BooleanField(default=False),
        ),
    ]
