# Generated by Django 6.0.3 on 2026-05-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_proposal_proposalitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='proposal_tittle',
            new_name='proposal_title',
        ),
    ]
