# Generated by Django 6.0.3 on 2026-05-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_proposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=10),
        ),
    ]
