# Generated by Django 6.0.4 on 2026-05-05 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_lead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
