# Generated by Django 6.0.4 on 2026-05-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_delete_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('call_status', models.CharField(choices=[('called', 'Not Called'), ('not_called', 'Not Called')], default='not_called', max_length=20)),
                ('attend_status', models.CharField(choices=[('attended', 'Attended'), ('not_attended', 'Not Attended')], default='not_attended', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
